const phoneCodes = [
  { label: 'United States (+1)', value: '+1' },
  { label: 'United Kingdom (+44)', value: '+44' },
  { label: 'Canada (+1)', value: '+1' },
  { label: 'Australia (+61)', value: '+61' },
  { label: 'India (+91)', value: '+91' },
  { label: 'Germany (+49)', value: '+49' },
  { label: 'France (+33)', value: '+33' },
  { label: 'Japan (+81)', value: '+81' },
  { label: 'Russia (+7)', value: '+7' },
  { label: 'China (+86)', value: '+86' },
  { label: 'Brazil (+55)', value: '+55' },
  { label: 'South Africa (+27)', value: '+27' },
  { label: 'Mexico (+52)', value: '+52' },
  { label: 'Argentina (+54)', value: '+54' },
  { label: 'Nigeria (+234)', value: '+234' },
  { label: 'Egypt (+20)', value: '+20' },
  { label: 'Indonesia (+62)', value: '+62' },
  { label: 'Pakistan (+92)', value: '+92' },
  { label: 'Bangladesh (+880)', value: '+880' },
  { label: 'Turkey (+90)', value: '+90' },
  { label: 'Philippines (+63)', value: '+63' },
  { label: 'Vietnam (+84)', value: '+84' },
  { label: 'Italy (+39)', value: '+39' },
  { label: 'Spain (+34)', value: '+34' },
  { label: 'Poland (+48)', value: '+48' },
  { label: 'Netherlands (+31)', value: '+31' },
  { label: 'Belgium (+32)', value: '+32' },
  { label: 'Sweden (+46)', value: '+46' },
  { label: 'Norway (+47)', value: '+47' },
  { label: 'Switzerland (+41)', value: '+41' },
  { label: 'Denmark (+45)', value: '+45' },
  { label: 'Austria (+43)', value: '+43' },
  { label: 'Greece (+30)', value: '+30' },
  { label: 'Portugal (+351)', value: '+351' },
  { label: 'Ireland (+353)', value: '+353' },
  { label: 'Israel (+972)', value: '+972' },
  { label: 'Saudi Arabia (+966)', value: '+966' },
  { label: 'United Arab Emirates (+971)', value: '+971' },
  { label: 'Singapore (+65)', value: '+65' },
  { label: 'Malaysia (+60)', value: '+60' },
  { label: 'South Korea (+82)', value: '+82' },
  { label: 'New Zealand (+64)', value: '+64' },
  { label: 'Hong Kong (+852)', value: '+852' },
  { label: 'Thailand (+66)', value: '+66' },
  { label: 'Taiwan (+886)', value: '+886' },
  { label: 'Czech Republic (+420)', value: '+420' },
  { label: 'Hungary (+36)', value: '+36' },
  { label: 'Finland (+358)', value: '+358' },
  { label: 'Chile (+56)', value: '+56' },
  { label: 'Colombia (+57)', value: '+57' },
  { label: 'Peru (+51)', value: '+51' },
  { label: 'Venezuela (+58)', value: '+58' },
  { label: 'Romania (+40)', value: '+40' },
  { label: 'Ukraine (+380)', value: '+380' },
  { label: 'Belarus (+375)', value: '+375' },
  { label: 'Kazakhstan (+7)', value: '+7' },
  { label: 'Uzbekistan (+998)', value: '+998' },
  { label: 'Morocco (+212)', value: '+212' },
  { label: 'Algeria (+213)', value: '+213' },
  { label: 'Tunisia (+216)', value: '+216' },
];

export default phoneCodes;
